# -*- coding: utf-8 -*-
"""Tugas2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUW8wPhQXVuX22nHoEuLaOT4baU1Z8vy
"""

print("Pilih part! \n1. Part A\n2. Part B")
pilihan = int(input("Pilihan Anda: "))

#A/B?
import os
os.system('cls')

#A
if pilihan == 1:
    n = int(input("Masukkan n: "))
    for i in range(n):
        print(i**2)

#B
elif pilihan == 2:
    n = int(input("Masukkan n: "))
    for i in range(n):
        if i % 2 == 1 or i == 0:
            print(i**2)
else:
    print("Undefined")